# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(IAM Data etc Fat Configuration) configuration. ####
#
spring:
  # Spring datasource configuration.
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      jdbcUrl: ${IAM_DB_URL:jdbc:mysql://rds.iam.wl4g.fat:3306/iam?useunicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true}
      username: ${IAM_DB_USER:iam}
      password: ${IAM_DB_PASSWD:123456}
      connectionTimeout: 30000
      idleTimeout: 600000
      initializationFailTimeout: 1
      minimumIdle: 10
      maxLifetime: 1800000
      maximumPoolSize: 100
      validationTimeout: 5000
      leakDetectionThreshold: 0
#    druid:
#      url: ${IAM_DB_URL:jdbc:mysql://rds.iam.wl4g.fat:3306/iam?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true}
#      username: ${IAM_DB_USER:iam}
#      password: ${IAM_DB_PASSWD:123456}
#      initial-size: 10
#      max-active: 100
#      min-idle: 10
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      filters: stat,wall
#      log-slow-sql: true
